sudo: required
services: 
  - docker

  before-install:
 - docker build -t  laxman13/docker-reactapp -f Dockerfile.dev .

 script:
 - docker run laxman13/docker-reactapp npm run test -- --coverage 


